title: Lumen
baseURL: /
params:
  accent_color: yellow
  color_scheme: light
  footer:
    content: '&copy; Stackbit-Exto. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: /images/3_thumb.jpg
    title: Albinia 4/10 Novembre
disableKinds:
  - RSS
